### ISSUE TITLE
Remaining Productionization Tasks Checklist

### ISSUE THREAD

**Issue by aitrean** [aitrean/typ3#10]
List of tasks that need to be finished before typ3 supports the full set of contract, filter, and node functionality. 

- [ ] #2 Add event handling
- [ ] #7 Support raw transaction creation for signing.
- [ ] #9 Clean up codebase
- [ ] #11 Function Overloading 
- [ ] #12 Fallback Support
